export const SdkResultValues = {
  USER_SHARED_CREDENTIALS: 'USER_SHARED_CREDENTIALS',
  USER_OPTED_OUT: 'USER_OPTED_OUT',
  NO_CREDENTIALS_FOUND: 'NO_CREDENTIALS_FOUND',
  RISK_SCORE_TOO_HIGH: 'RISK_SCORE_TOO_HIGH',
  MAX_INPUT_ATTEMPTS_EXCEEDED: 'MAX_INPUT_ATTEMPTS_EXCEEDED',
  MAX_VERIFICATION_CODE_ATTEMPTS_EXCEEDED: 'MAX_VERIFICATION_CODE_ATTEMPTS_EXCEEDED',
} as const;

export const SdkErrorReasons = {
  SESSION_TIMEOUT: 'SESSION_TIMEOUT',
  INVALID_SESSION_KEY: 'INVALID_SESSION_KEY',
  SHARE_CREDENTIALS_ERROR: 'SHARE_CREDENTIALS_ERROR',
} as const;

export const PossibleEventTypes = {
  VERIFIED_CLIENT_SDK_VIEWPORT_READY: 'VERIFIED_CLIENT_SDK_VIEWPORT_READY',
  VERIFIED_CLIENT_SDK_VIEWPORT_RESIZE: 'VERIFIED_CLIENT_SDK_VIEWPORT_RESIZE',
  VERIFIED_CLIENT_SDK_USER_OPTED_OUT: 'VERIFIED_CLIENT_SDK_USER_OPTED_OUT',
  VERIFIED_CLIENT_SDK_NO_CREDENTIALS_FOUND: 'VERIFIED_CLIENT_SDK_NO_CREDENTIALS_FOUND',
  VERIFIED_CLIENT_SDK_RISK_SCORE_TOO_HIGH: 'VERIFIED_CLIENT_SDK_RISK_SCORE_TOO_HIGH',
  VERIFIED_CLIENT_SDK_MAX_INPUT_ATTEMPTS_EXCEEDED:
    'VERIFIED_CLIENT_SDK_MAX_INPUT_ATTEMPTS_EXCEEDED',
  VERIFIED_CLIENT_SDK_MAX_VERIFICATION_CODE_ATTEMPTS_EXCEEDED:
    'VERIFIED_CLIENT_SDK_MAX_VERIFICATION_CODE_ATTEMPTS_EXCEEDED',
  VERIFIED_CLIENT_SDK_FORM_SUBMISSION: 'VERIFIED_CLIENT_SDK_FORM_SUBMISSION',
  VERIFIED_CLIENT_SDK_FORM_SUBMISSION_ERROR: 'VERIFIED_CLIENT_SDK_FORM_SUBMISSION_ERROR',
  VERIFIED_CLIENT_SDK_INVALID_SESSION_KEY: 'VERIFIED_CLIENT_SDK_INVALID_SESSION_KEY',
  VERIFIED_CLIENT_SDK_SESSION_TIMEOUT: 'VERIFIED_CLIENT_SDK_SESSION_TIMEOUT',
} as const;

export const EventSource = 'Verified.Client@1.3.0' as const;
